### ISSUE TITLE
Next Prev Arrow Buttons

### ISSUE THREAD

**Issue by sagarbhosale91** [Wlada/angular-carousel-3d#10]
One more feature I am waiting for.
Is there any arrow functionality in current slider.
I want to change slides using next/prev arrows.

**Comment by Wlada** [comment]
Hi @sagarbhosale91 

Yes, that's in the list. I have that already implemented in some of local version.  I Will update repository during this weekend.

**Comment by sagarbhosale91** [comment]
Hi @Wlada 

Thanks for update.. its nice feature to have.. :-)

**Comment by Wlada** [comment]
Hi, @sagarbhosale91 

This feature is committed
