### ISSUE TITLE
User should be able to disable slide looping.

### ISSUE THREAD

**Issue by vrocha** [Wlada/angular-carousel-3d#12]
It would be really nice if both options existed, one where you can keep going to the next slide forever (you just keep looking through your slides), and the other where you run out of slides and all of the slides are either to the left or right or the current side.

**Comment by Wlada** [comment]
Hi Victor,

Yes, totally . Feel free to contribute if you have ideas. 
I will also have this feature on my radar.

**Comment by vrocha** [comment]
Hi Vladimir,

I am still reading through the code to see what's the best way to do this.

**Comment by Wlada** [comment]
I'm not sure what's the best way to implement this. Carousel instance has leftSlides and rightSlides properties, Some logic around that maybe, or around rightOutSlides. 
To count number of slides and to prevent carousel animation. 
What is important to know is that slide change can be triggered when you click on carousel item, so preventing click on arrows won't be enough.
This is just idea about implementation, maybe you find something better. I will try asap to look more

**Comment by vrocha** [comment]
I didn't really find a straight forward approach to solve this. I am still thinking about it. I should have some free time this weekend.

**Comment by webservconsultant** [comment]
Is there any update on this enhancement? Would really love to see this feature added.

**Comment by Wlada** [comment]
Added loop option 

loop: false - to disable looping
clicking: false - to disable click on slide navigation
