### ISSUE TITLE
Multiple slides have class "current"

### ISSUE THREAD

**Issue by vrocha** [Wlada/angular-carousel-3d#13]
Not sure if this is a "feature" or a bug, but if you click on a slide that is not immediately next to the one in the middle, you get multiple slides with the class current. It would make sense to always have a single "current" slide.

This is the line that is causing this bug: https://github.com/Wlada/angular-carousel-3d/blob/master/dist/carousel-3d.js#L270. Instead of only iterating over the leftSlides we want to iterate over all the slides to remove the class from all of them.

**Comment by Wlada** [comment]
Thanks for catching this. This problem was created after some code refactoring. It's fixed now, and everything looks good. If you want check on demo page.
