### ISSUE TITLE
Can't use border value of 0 as an option

### ISSUE THREAD

**Issue by vrocha** [Wlada/angular-carousel-3d#14]
There is a line of code that is evaluating the value for the border to be equal to params.border || 5, since parms.border is 0 then the expression evaluates to 5.

**Comment by Wlada** [comment]
Hi @victor-rocha 

Good catch.  This should be easy to fix, and I will do it ASAP. Thanks

**Comment by Wlada** [comment]
Done. Changed default value to 0 what was quickest and maybe most logical option. 
If you don't define border, it should be 0.
