### ISSUE TITLE
How to set startslide programatically?

### ISSUE THREAD

**Issue by webservconsultant** [Wlada/angular-carousel-3d#19]
I have some business logic in my controller to determine which slide be the beginning one? There is no  UI but should happen in background? How do you do that?

**Comment by Wlada** [comment]
Hi,

Maybe not so elegant solution but to create some flag rendered = false and add ng-if directive on carousel wrapper. Once you calculate your start slide, set rendered to true. I'm not sure but that may help you to render carousel once you get start slide.
Check plunker for better explanation  http://plnkr.co/edit/tulHK7wrOFxh4RIpSKau?p=preview

**Comment by webservconsultant** [comment]
this helped me resolve the issue. I have a date control that determines the current slide. so whenever there is a date change I am removing and adding back the carousel using ng-if directive. You can close this issue.

**Comment by Wlada** [comment]
great. this one is closed
