### ISSUE TITLE
Cant bind array of objects

### ISSUE THREAD

**Issue by JovanyRocha** [Wlada/angular-carousel-3d#2]
If i have in my view:

```
<div ng-controller="CarouselController">
    <div carousel3d ng-model="arrayOfObjects"></div>
</div>
```

And in the controller:

```
$scope.arrayOfObjects = [
  {src: ''souce_url'},
  {src: ''souce_url'},
  {src: ''souce_url'},
];
```

Why could happen this error in console?

![issue](https://cloud.githubusercontent.com/assets/10714110/11251731/d6a3fd46-8def-11e5-9c8c-320da8e22351.png)
*Notes:
-Controller is working well.
-Array is visible in view.
-Array is not empty.

**Comment by Wlada** [comment]
Hi Jovany 

What version of angular you are using ??

**Comment by JovanyRocha** [comment]
close issue, yeah, it was the crush of versions. thanks a lot.
