### ISSUE TITLE
Problem with initialisation

### ISSUE THREAD

**Issue by snecz** [Wlada/angular-carousel-3d#22]
Hello,
I'm trying to implement angular carousel into my Wordpress. I've managed to add js scripts but can't make it working. I've added demo.js from your demo site, initializing html and images but I can't make it shwo up. Could someone take a look at my website?

**Comment by Wlada** [comment]
Hi @snecz 

It's really hard to help if you don't give more details. First of all you must check did you load angular in your application. Can you post your website url here ?

**Comment by snecz** [comment]
Hi @Wlada,
It'd be great if you could take a look at this http://www.mazuraqua.pl/234-2/

**Comment by Wlada** [comment]
angular is undefined on that page, but on homepage angular is loaded. 
Make sure that angular is loaded on page where you wan't to implement carousel. 
Also if you wan't to swipe events with carousel you need to load swipe.js library which is required for carousel 3d.

Check  "Usage" section on carousel github homepage

To check is angular loaded the easiest way is to open developer tools console and to type angular

**Comment by snecz** [comment]
It's strange as footer is the same for website. And there's angular.js, angular-swipe.js, carousel-3d.js loaded

**Comment by Wlada** [comment]
Bug is not on carousel module
