### ISSUE TITLE
Interval

### ISSUE THREAD

**Issue by Roycohen** [Wlada/angular-carousel-3d#23]
Hi Guys,

there is one request I want and one bug I want to report.
First, the bug:
Interval is being created without removing it when page change.
I would probably solve it in $destroy event and remove the interval or something.
It would be great if you can fix it.

Second, is there a way to communicate with the carousel. I want to start the carousel with automatic loop and stop and resume it on user behaviour. if he clicks on something or hover the carousel.

Waiting for your reply.

**Comment by Wlada** [comment]
Hi @Roycohen 

Thanks for catching that. Bug reported at: #24 

I also created one more task to implement pausing carousel on hover #25 

Now, to enable controlling carousel out of carousel is not what I imagine in the first place. If you have idea how this can be done, feel free to fork the repository 

 #24 and #25 it's on me and I will try to do it once I get some free time. 

Cheers

**Comment by Roycohen** [comment]
Hi @Wlada Thanks!
Looking forward for this to be resolved.
