### ISSUE TITLE
how to prevent slide to next

### ISSUE THREAD

**Issue by wzhsh90** [Wlada/angular-carousel-3d#41]
i wan to prevent the slide to the next,  but the mothod beforeChange can not prevent it. how can solve this problem ?

**Comment by Luwangel** [comment]
It's not possible at the moment but I'll add this feature asap.

**Comment by Luwangel** [comment]
I've made a [PR](https://github.com/Wlada/angular-carousel-3d/pull/46/commits/74e507457b3c272c4781ce440f6b69168f80800f) containing your suggestion.

**Comment by Luwangel** [comment]
Added in [v0.3.0](https://github.com/Wlada/angular-carousel-3d/releases/tag/0.3.0)
