### ISSUE TITLE
Bower dependancies angular version

### ISSUE THREAD

**Issue by olefrancois** [Wlada/angular-carousel-3d#44]
Hello, 

I'm using Angular 1.4.7 and since your last commit, I can't install my bower dependancies because of the new version of angular required.

It's possible to publish a tag for the previous version of angular ? 
I can't upgrade my Angular version on my project.

Thanks.

**Comment by Luwangel** [comment]
Hello,

I've made two releases (with and without the package update). So you can use the previous one in your project : [tag 0.1.2](https://github.com/Wlada/angular-carousel-3d/releases/tag/0.1.2).

Regards,
Luwangel
