### ISSUE TITLE
How to set the foreground image from the controller.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [Wlada/angular-carousel-3d#5]
First of all thanks for this plugin.
I have a list of images and i am able to use this plugin to some extent. I have a need that i should be able to set the foreground image dynamically from the code.
Let's say i have an array of images `$scope.arr = [{1},{2},{3},{4}]`. So here the default image will be the first item (`{1}`) in the array. But i want to change the first image, which will show as a foreground image to the `{3}` from the code dynamically, without changing the order of the objects in the array.

And also the images in the array are showing from middle to left and then to right. Can we show the images in the following order?
`middle, right, right+1, left+1, left etc..`

How can i do that? could you please guide me on this?

**Comment by Wlada** [comment]
Hi,

Start slide option was OK few days ago, but right not is not working as I see. Tomorrow I can fix problem with startSlide option and then you will be able to set start slide. currentIndex is present inside Service and I think that's not big job.

For different rendering try to define "dir" option parameter. Right now default is 'ltr' and and that is affecting on rendering order. If you pass anything else as "dir"  parameter, rendering will be from right to left. 

I'm not sure about all of this and check tomorrow.  If everything works as expected I will update documentation. . Feel free to contribute if you have ides. 

Cheers

**Comment by rajeshwarpatlolla** [comment]
Thanks for your reply. The direction issue is resolved and working fine with the property as you mentioned. And also if you get a chance to make the startslide option in complete working mode, please let me know.

**Comment by Wlada** [comment]
Hi @rajeshwarpatlolla ,

Sorry for bit late response, I had sprint delivery previous week.
Code is updated and you can pull changes from master. 

startSlide property will resolve problem with start slide. 

If everything is OK can you please close the issue, or If you have any more questions feel free to ask.

**Comment by rajeshwarpatlolla** [comment]
I pulled the latest code. Checking it. Once it works i will close this issue.

**Comment by rajeshwarpatlolla** [comment]
Getting an error `TypeError: Cannot read property 'attr' of undefined`@ line # 206 in carousel-3d.js, while trying to play with the new version which is pulled from master. Because of that i am unable to see the images at all.

**Comment by Wlada** [comment]
Hi,

I updated demo page with latest changes and everything works fine. 
http://vladimirbujanovic.com/angular-carousel-3d/demo/demo.html

Now on demo page you can set carousel direction (orientation) and you can set Start slide (first is 0)

I'm not using jquery on demo, but I'm sure that this plugin works with or without jquery.

Can you please check again your pull requests. It should be ok.
