### ISSUE TITLE
Getting an error, while playing with the slider.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [Wlada/angular-carousel-3d#8]
I was playing with the plugin and sometimes it's showing an error.
Below is the error.
`
TypeError: Cannot read property 'attr' of undefined
    at render (carousel-3d.js:206)
    at init (carousel-3d.js:173)
    at carousel-3d.js:84
    at angular.js:17855
    at completeOutstandingRequest (angular.js:5507)
    at angular.js:5784
`

**Comment by Wlada** [comment]
Hi @rajeshwarpatlolla 

Looking at the error I can say that in some point carousel item is missing.
Can you create jsfiddle link? 

I tried to break demo page by adding and removing items from carousel, but everything works fine.

**Comment by Wlada** [comment]
Hi @rajeshwarpatlolla 

Did you found problem ? I can't reproduce problem

**Comment by rajeshwarpatlolla** [comment]
I still have this issue, this is happening when we dynamically add and delete the slides. It happens 1 out of 10 times approx.

**Comment by Wlada** [comment]
Hi @rajeshwarpatlolla 

Will try to reproduce this and to find solution for you. Give me couple of days, probably will spend some time during weekend. 

You will be informed

**Comment by Wlada** [comment]
Can't reproduce this one.
